CONFIG_MODEL_NAME: str = "test4"
CONFIG_MODEL_FORCE_PASSAGE: list[int] = [0]
CONFIG_TOKENIZER: str = "single_characters_tokenizer"
PRINTDIMS: bool = False

MAX_LOADED_BLOCKS = 5
BLOCKS_TO_REMOVE = 1

CONTEXT_LENGTH = 16
EMBEDDING_DIM = CONTEXT_LENGTH * 4
HIDDEN_DIM = EMBEDDING_DIM
NUMBER_OF_BLOCKS = 20
NUMBER_OF_ATTENTION_HEADS = 1
